mongo_connect =  {\n",
    "        \"database\": \"<>\",\n",
    "        \"shards\": [\n",
    "            \"<>.azure.mongodb.net:27017\",\n",
    "            \"<>.azure.mongodb.net:27017\",\n",
    "            \"<>.azure.mongodb.net:27017\"\n",
    "        ],\n",
    "        \"test_db\": \"test\",\n",
    "        \"properties\": [\n",
    "            \"ssl=true\",\n",
    "            \"replicaSet=<>\",\n",
    "            \"authSource=admin\",\n",
    "            \"retryWrites=true\",\n",
    "            \"w=majority\"\n",
    "        ],\n",
    "        \"user\": \"<>\",\n",
    "        \"secretScopeName\": \"<>\",\n",
    "        \"secretScopeKey\": None\n",
    "    }\n",
    "\n",
    "mongo_config = json.dumps(mongo_connect,default=str)\n",
    "\n",
    "collection_name = \"<>\"\n",
    "\n",
    "topic_name = dbutils.widgets.get(\"topicName\")\n",
    "prd_group = dbutils.widgets.get(\"productGroup\")\n",
    "\n",
    "print(\"Topic Name :\"+topic_name)\n",
    "print(\"Product group :\"+prd_group)\n",
    "print(\"Collection group :\"+collection_name)"
   ]
